"""Write theme/styles/plot-tokens.css from plot_styles.py.

plot_styles.py is the one source for chart colour and type. Vue charts read
these variables and nothing else, so they cannot drift from the matplotlib
figures. deck.mjs reruns this whenever plot_styles.py is newer than the CSS.

    python3 theme/export_tokens.py
"""
import os
import re

import plot_styles as ps

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "styles", "plot-tokens.css")
PT_TO_PX = 4 / 3  # an SVG at 96 px per inch, see SLIDE_FIGSIZE


def kebab(name: str) -> str:
    return name.lower().replace("_", "-")


def main() -> None:
    lines = [
        "/* GENERATED by theme/export_tokens.py from theme/plot_styles.py.",
        "   Do not edit. Change plot_styles.py and the deck regenerates this. */",
        ":root{",
    ]
    for name, value in vars(ps).items():
        if name.isupper() and isinstance(value, str) and re.fullmatch(r"#[0-9A-Fa-f]{6}", value):
            lines.append(f"  --plot-{kebab(name)}:{value};")
    for i, colour in enumerate(ps.COLOR_CYCLE):
        lines.append(f"  --plot-cycle-{i}:{colour};")

    slide = ps._FONT_TIERS["slide"]
    sizes = {
        "tick": slide["xtick.labelsize"],
        "label": slide["axes.labelsize"],
        "legend": slide["legend.fontsize"],
        "title": slide["axes.titlesize"],
    }
    for role, pt in sizes.items():
        lines.append(f"  --plot-size-{role}:{round(pt * PT_TO_PX)}px;")
    lines.append('  --plot-font:Arial,"Liberation Sans",sans-serif;')
    lines.append("  --plot-weight:bold;")
    lines.append("}")

    with open(OUT, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {os.path.relpath(OUT)}")


if __name__ == "__main__":
    main()
